apiVersion: v1
kind: Secret
metadata:
  name: todo
type: Opaque
stringData:
  MYSQL_HOST: db
  MYSQL_PORT: "80"
  MYSQL_USER: myuser
  MYSQL_PASSWORD: myuserpass
  MYSQL_DATABASE: todo_app
  DATABASE_URL: mysql://myuser:myuserpass@db:80/todo_app
  MYSQL_ROOT_PASSWORD: rootpass
